### PR TITLE
add FeedForwardTrackingController and a few minor updates

### PR DESCRIPTION
**Pull request by alexxlzhou**
Add a FeedForwardTrackingController that produces a feed-forward control signal for any actuator, based on a pid tracking of a model state.
Add interface LuaDof::muscle_moment.
Add a positive muscle work in EffortMeasure, however, this may not be needed and can be done with Lua script after LuaDof::muscle_moment is added.

### CODE REVIEW

**Comment by tgeijten** [comment]
Thank you! The code looks good and ready to merge. The name `FeedForwardTrackingController` is a bit confusing though, since it's not actually a feed-forward controller but a feedback controller. Could you perhaps rename it to just `TrackingController`?

**Comment by alexxlzhou** [comment]
Certainly, should I make the change from my side and send another pull request, or you can do it from your end?

**Comment by tgeijten** [comment]
Yes, could you do it from your end, please? You should be able to make the change without creating a new pull request.

**Comment by alexxlzhou** [comment]
Ok, changes were made. Thanks.

**Pull request merged**
